[package]
name="ugentthesis"
version="0.1.3"
entrypoint="lib/lib.typ"
authors=["Lieven Vandevelde"]
license = "MIT"
description="Theses following guidelines at Ghent University and using additional features compared to standard Typst element functions."
repository="https://github.com/lvandevelde/Typst-UGent-thesis"
categories=["thesis","model","layout"]
keywords = ["template", "thesis", "Ghent University"]


[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "template/thumbnail.png"


