[package]
name="ugentthesis"
version="0.1.1"
authors=["Lieven Vandevelde"]
entrypoint="lib/lib.typ"
description="Package and template for theses"
repository="https://github.com/lvandevelde/Typst-UGent-thesis"
categories=["thesis","model","layout"]
keywords = ["template", "thesis"]
license = "MIT"

[template]
path = "template"
entrypoint = "thesis.typ"


