[package]
name="ugentthesis"
version="0.1.1"
entrypoint="lib/lib.typ"
authors=["Lieven Vandevelde"]
license = "MIT"
description="Master's and doctoral theses based on guidelines at Ghent University."
repository="https://github.com/lvandevelde/Typst-UGent-thesis"
categories=["thesis","model","layout"]
keywords = ["template", "thesis", "Ghent University"]


[template]
path = "template"
entrypoint = "thesis.typ"
thumbnail = "template/thumbnail.png"


